name: flutter_sqlite_notes_demo
description: A new Flutter project.

# This is the part you need to add/fix
environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.3+1
  path: ^1.9.0
  provider: ^6.1.2